export interface ServiceInfo {
  key: string;
  name: string;
  description: string;
  href: string;
  aliases: string[];
}

export const services: ServiceInfo[] = [
  {
    key: "s3",
    name: "S3",
    description: "Scalable object storage",
    href: "/services/s3",
    aliases: ["object storage", "bucket", "blob", "static hosting", "simple storage service"],
  },
  {
    key: "lambda",
    name: "Lambda",
    description: "Run code without servers",
    href: "/services/lambda",
    aliases: ["serverless", "function", "faas", "run code"],
  },
  {
    key: "ec2",
    name: "EC2",
    description: "Virtual servers in the cloud",
    href: "/services/ec2",
    aliases: ["compute", "instance", "vm", "virtual machine", "server", "elastic compute cloud"],
  },
  {
    key: "dynamodb",
    name: "DynamoDB",
    description: "Managed NoSQL database",
    href: "/services/dynamodb",
    aliases: ["nosql", "table", "key value", "document db"],
  },
  {
    key: "rds",
    name: "RDS",
    description: "Managed relational databases",
    href: "/services/rds",
    aliases: ["sql", "relational", "postgres", "mysql", "database", "relational database service"],
  },
  {
    key: "elasticache",
    name: "ElastiCache",
    description: "In-memory caching",
    href: "/services/elasticache",
    aliases: ["cache", "redis", "memcached", "in-memory", "valkey"],
  },
  {
    key: "sqs",
    name: "SQS",
    description: "Managed message queues",
    href: "/services/sqs",
    aliases: ["queue", "message", "fifo", "simple queue service"],
  },
  {
    key: "sns",
    name: "SNS",
    description: "Pub/sub messaging",
    href: "/services/sns",
    aliases: ["pubsub", "topic", "notification", "push", "simple notification service"],
  },
  {
    key: "apigateway",
    name: "API Gateway",
    description: "HTTP and REST APIs",
    href: "/services/apigateway",
    aliases: ["api", "rest", "http", "endpoint"],
  },
  {
    key: "eventbridge",
    name: "EventBridge",
    description: "Event buses and rules",
    href: "/services/eventbridge",
    aliases: ["events", "event bus", "rules", "cron", "schedule", "cloudwatch events"],
  },
  {
    key: "iam",
    name: "IAM",
    description: "Identity and access management",
    href: "/services/iam",
    aliases: ["identity", "permissions", "roles", "users", "policy"],
  },
  {
    key: "cognito",
    name: "Cognito",
    description: "User authentication and identity",
    href: "/services/cognito",
    aliases: ["auth", "authentication", "user pool", "login", "identity", "sign in"],
  },
  {
    key: "ssm",
    name: "Parameter Store",
    description: "Configuration and secrets",
    href: "/services/ssm",
    aliases: ["parameter store", "secrets", "config", "ssm", "systems manager"],
  },
  {
    key: "cloudwatch",
    name: "CloudWatch",
    description: "Logs and metrics",
    href: "/services/cloudwatch",
    aliases: ["logs", "metrics", "monitoring", "alarms"],
  },
  {
    key: "appconfig",
    name: "AppConfig",
    description: "Feature flags and configuration",
    href: "/services/appconfig",
    aliases: ["config", "feature flags", "application configuration", "deployment"],
  },
  {
    key: "cloudfront",
    name: "CloudFront",
    description: "Content delivery network",
    href: "/services/cloudfront",
    aliases: ["cdn", "distribution", "edge", "content delivery"],
  },
  {
    key: "athena",
    name: "Athena",
    description: "Query data with SQL",
    href: "/services/athena",
    aliases: ["query", "sql", "analytics", "presto", "data lake"],
  },
  {
    key: "kinesis",
    name: "Kinesis",
    description: "Real-time data streams",
    href: "/services/kinesis",
    aliases: ["stream", "streaming", "shard", "data stream", "real-time", "firehose"],
  },
  {
    key: "stepfunctions",
    name: "Step Functions",
    description: "Visual workflows and state machines",
    href: "/services/stepfunctions",
    aliases: ["state machine", "workflow", "sfn", "orchestration", "asl", "executions"],
  },
  {
    key: "ses",
    name: "SES",
    description: "Send and receive email",
    href: "/services/ses",
    aliases: ["email", "mail", "smtp", "identity", "simple email service"],
  },
  {
    key: "route53",
    name: "Route 53",
    description: "DNS and domain management",
    href: "/services/route53",
    aliases: ["dns", "domain", "hosted zone", "record", "nameserver"],
  },
  {
    key: "ecs",
    name: "ECS",
    description: "Run and manage containers",
    href: "/services/ecs",
    aliases: ["container", "cluster", "fargate", "task", "service", "docker", "elastic container service"],
  },
  {
    key: "ecr",
    name: "ECR",
    description: "Container image registry",
    href: "/services/ecr",
    aliases: ["registry", "image", "docker", "container", "repository", "elastic container registry"],
  },
  {
    key: "secretsmanager",
    name: "Secrets Manager",
    description: "Store and retrieve secrets",
    href: "/services/secretsmanager",
    aliases: ["secret", "credentials", "password", "api key", "rotation"],
  },
  {
    key: "kms",
    name: "KMS",
    description: "Encryption keys",
    href: "/services/kms",
    aliases: ["key", "encryption", "crypto", "cmk", "key management service"],
  },
  {
    key: "cloudformation",
    name: "CloudFormation",
    description: "Infrastructure as code stacks",
    href: "/services/cloudformation",
    aliases: ["stack", "iac", "template", "cfn", "infrastructure as code", "provisioning"],
  },
  {
    key: "vpc",
    name: "VPC",
    description: "Virtual networks and subnets",
    href: "/services/vpc",
    aliases: ["network", "subnet", "security group", "route table", "cidr", "virtual private cloud", "networking"],
  },
  {
    key: "elbv2",
    name: "Load Balancers",
    description: "Application and network load balancers",
    href: "/services/elbv2",
    aliases: ["elb", "alb", "nlb", "load balancer", "elastic load balancing", "listener", "target group"],
  },
  {
    key: "acm",
    name: "Certificate Manager",
    description: "TLS/SSL certificates",
    href: "/services/acm",
    aliases: ["acm", "certificate", "tls", "ssl", "https", "cert"],
  },
];
